export const ITEMS_PROJECTS = [
  {
    id: '1',
    title: 'Project 1',
    technologies: ['React', 'TypeScript', 'Tailwind CSS'],
    description: 'This is a project description',
    image: '/image/project/project_1.png',
    to: '/project/1',
  },
  {
    id: '2',
    title: 'Project 2',
    technologies: ['React', 'TypeScript', 'Tailwind CSS'],
    description: 'This is a project description',
    image: '/image/project/project_1.png',
    to: '/project/1',
  },
  {
    id: '3',
    title: 'Project 3',
    technologies: ['React', 'TypeScript', 'Tailwind CSS'],
    description: 'This is a project description',
    image: '/image/project/project_1.png',
    to: '/project/1',
  },
  {
    id: '4',
    title: 'Project 4',
    technologies: ['React', 'TypeScript', 'Tailwind CSS'],
    description: 'This is a project description',
    image: '/image/project/project_1.png',
    to: '/project/1',
  },
  {
    id: '5',
    title: 'Project 5',
    technologies: ['React', 'TypeScript', 'Tailwind CSS'],
    description: 'This is a project description',
    image: '/image/project/project_1.png',
    to: '/project/1',
  },
  {
    id: '6',
    title: 'Project 6',
    technologies: ['React', 'TypeScript', 'Tailwind CSS'],
    description: 'This is a project description',
    image: '/image/project/project_1.png',
    to: '/project/1',
  },
]
